version: 2
updates:
  - package-ecosystem: "npm"
    directories:
      - "/"
    versioning-strategy: increase
    schedule:
      interval: "weekly"
    cooldown:
      semver-major-days: 90
      semver-minor-days: 21
      semver-patch-days: 7
    labels:
      - "build"
  - package-ecosystem: "npm"
    directories:
      - "shieldlib/"
    versioning-strategy: widen
    schedule:
      interval: "weekly"
    cooldown:
      semver-major-days: 90
      semver-minor-days: 21
      semver-patch-days: 7
    labels:
      - "build"
